version: '3.5'

services:
  postgres:
    image: postgres:15
    container_name: zabbix-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    ports:
      - "10051:10051"
    volumes:
      - ./data/zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts
      - ./data/zabbix-server/externalscripts:/usr/lib/zabbix/externalscripts
      - ./data/zabbix-server/modules:/var/lib/zabbix/modules
      - ./data/zabbix-server/enc:/var/lib/zabbix/enc
      - ./data/zabbix-server/ssh_keys:/var/lib/zabbix/ssh_keys
      - ./data/zabbix-server/mibs:/var/lib/zabbix/mibs
      - ./data/zabbix-server/logs:/var/log/zabbix
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-frontend
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    ports:
      - "7575:8080"
    depends_on:
      - zabbix-server
      - postgres
    volumes:
      - ./data/zabbix-web/logs:/var/log/zabbix
    restart: always

  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zabbix-agent2
    environment:
      ZBX_HOSTNAME: "homelab-agent"
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "10050:10050"
    volumes:
      - ./data/zabbix-agent2/logs:/var/log/zabbix
    restart: always
