#writted by pardesi_cat
version; '3'
services:
  matrix:
    image: matrixdotorg/synapse:latest
    container_name: matrix_synapse
    restart:always
    user: "0:0"
    ports:
      - 8008:8008
    volumes:
      - ${PWD}/synapse-data:/data

