#written by Pardesi_Cat
version: '3'
services:
  gophish:
    image: gophish/gophish:latest
    container_name: gophish
    restart: unless-stopped
    ports:
      - 3333:3333
    environment:
     - GOPHISH_INITIAL_ADMIN_PASSWORD="adminn"
