version: '3'
 services:
  webhomer:
    image: b4bz/homer:latest
    container_name: webhomer
    restart: always
    volumes:
      - ${PWD}/web/:/www/assets/
    networks:
      - npm_default
networks:
  npm_default:
    name: npm_default
    external: true

