version: '3.8'

services:
  archivebox:
    image: archivebox/archivebox:latest
    restart: always
    ports:
      - 8484:8000
    volumes:
      - ./data:/data
      # ./data/personas/Default/chrome_profile/Default:/data/personas/Default/chrome_profile/Default
    environment:
      - ADMIN_USERNAME=pardesicat            # creates an admin user on first run with the given user/pass combo
      - ADMIN_PASSWORD=PCATarchive@
      - ALLOWED_HOSTS=*                   # set this to the hostname(s) you're going to serve the site from!
      - CSRF_TRUSTED_ORIGINS=http://localhost:8484  # you MUST set this to the server's URL for admin login and the REST API to work
      - PUBLIC_INDEX=True                 # set to False to prevent anonymous users from viewing snapshot list
      - PUBLIC_SNAPSHOTS=True             # set to False to prevent anonymous users from viewing snapshot content
      - PUBLIC_ADD_VIEW=False             # set to True to allow anonymous users to submit new URLs to archive
      - SEARCH_BACKEND_ENGINE=sonic       # tells ArchiveBox to use sonic container below for fast full-text search
      - SEARCH_BACKEND_HOST_NAME=sonic
      - SEARCH_BACKEND_PASSWORD=SomeSecretPasswordbysonic
      # - PUID=911                        # set to your host user's UID & GID if you encounter permissions issues
      # - PGID=911                        # UID/GIDs lower than 500 may clash with system uids and are not recommended
      # For options below, it's better to set in data/ArchiveBox.conf or use `docker compose run archivebox config --set SOME_KEY=someval` instead of setting here:
      # - MEDIA_MAX_SIZE=750m             # increase this filesize limit to allow archiving larger audio/video files
      # - TIMEOUT=60                      # increase this number to 120+ seconds if you see many slow downloads timing out
      # - CHECK_SSL_VALIDITY=True         # set to False to disable strict SSL checking (allows saving URLs w/ broken certs)
      # - SAVE_ARCHIVE_DOT_ORG=True       # set to False to disable submitting all URLs to Archive.org when archiving
      # - USER_AGENT="..."                # set a custom USER_AGENT to avoid being blocked as a bot
      # ...
      # For more info, see: https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#configuration

    # For ad-blocking during archiving, uncomment this section and the pihole service below
    # networks:
    #   - dns
    # dns:
    #   - 172.20.0.53

  archivebox_scheduler:
    image: archivebox/archivebox:latest
    restart: always
    command: schedule --foreground --update --every=day
    environment:
      # - PUID=911                        # set to your host user's UID & GID if you encounter permissions issues
      # - PGID=911
      - TIMEOUT=120                       # use a higher timeout than the main container to give slow tasks more time when retrying
      - SEARCH_BACKEND_ENGINE=sonic       # tells ArchiveBox to use sonic container below for fast full-text search
      - SEARCH_BACKEND_HOST_NAME=sonic
      - SEARCH_BACKEND_PASSWORD=SomeSecretPasswordbysonic
      # For other config it's better to set using `docker compose run archivebox config --set SOME_KEY=someval` instead of setting here
    volumes:
      - ./data:/data
    # cpus: 2                               # uncomment / edit these values to limit scheduler container resource consumption
    # mem_limit: 2048m
    # restart: always

  sonic:
    image: archivebox/sonic:latest
    restart: always
    expose:
      - 1491
    environment:
      - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
    volumes:
      # - ./sonic.cfg:/etc/sonic.cfg:ro    # mount to customize: https://raw.githubusercontent.com/ArchiveBox/ArchiveBox/stable/etc/sonic.cfg
      - ./data/sonic:/var/lib/sonic/store

  novnc:
    image: theasp/novnc:latest
    restart: always
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      # to view/control ArchiveBox's browser, visit: http://127.0.0.1:8080/vnc.html
      # restricted to access from localhost by default because it has no authentication
      - 127.0.0.1:8282:8080

#  nginx:
#    image: nginx:alpine
#    ports:
#      - 443:443
#      - 80:80
#    volumes:
#      - ./etc/nginx.conf:/etc/nginx/nginx.conf
#      - ./data:/var/www

  # pihole:
  #   image: pihole/pihole:latest
  #   ports:
  #     # access the admin HTTP interface on http://localhost:8090
  #     - 127.0.0.1:8090:80
  #   environment:
  #     - WEBPASSWORD=SET_THIS_TO_SOME_SECRET_PASSWORD_FOR_ADMIN_DASHBOARD
  #     - DNSMASQ_LISTENING=all
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #   networks:
  #     dns:
  #       ipv4_address: 172.20.0.53
  #   volumes:
  #     - ./etc/pihole:/etc/pihole
  #     - ./etc/dnsmasq:/etc/dnsmasq.d

  # wireguard:
  #   image: linuxserver/wireguard:latest
  #   network_mode: 'service:archivebox'
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   sysctls:
  #     - net.ipv4.conf.all.rp_filter=2
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   volumes:
  #     - /lib/modules:/lib/modules
  #     - ./wireguard.conf:/config/wg0.conf:ro

  # changedetection:
  #   image: ghcr.io/dgtlmoon/changedetection.io
  #   volumes:
  #     - ./data-changedetection:/datastore

  # pywb:
  #   image: webrecorder/pywb:latest
  #   entrypoint: /bin/sh -c '(wb-manager init default || test $$? -eq 2) && wb-manager add default /archivebox/archive/*/warc/*.warc.gz; wayback;'
  #   environment:
  #     - INIT_COLLECTION=archivebox
  #   ports:
  #     - 8686:8080
  #   volumes:
  #     - ./data:/archivebox
  #     - ./data/wayback:/webarchive

networks:
  dns:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
