version: '3'
services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: always
    volumes:
      - ${PWD}/searxng:/etc/searxng
    environment:
      - INSTANCE_NAME=Pardesi-Search
      - BASE_URL=https://pardesicat.xyz/
      - AUTOCOMPLETE=google
      - AUTOCOMPLETE_MIN=2
    networks:
      - npm_default
networks:
  npm_default:
    name: npm_default
    external: true
